"""Geometry and visual-quality helpers for plate crops.

This module keeps the plate ROI logic isolated from the OCR engines so the
main orchestration file can stay lean. It is intentionally conservative:
it prefers small, explainable transformations and leaves heavy OCR-specific
preprocessing to the engine variants.
"""

from __future__ import annotations

import os
import math

import cv2
import numpy as np

from utils import plate_detector_calibration as plate_detector_calibration_module


def _clamp(value, minimum, maximum):
    return max(minimum, min(maximum, value))


def _parse_float(value, default):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _parse_int(value, default):
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


PLATE_DETECTION_CALIBRATION = plate_detector_calibration_module.load_plate_detector_calibration()


def _calibration_value(*keys, default=None):
    current = PLATE_DETECTION_CALIBRATION
    for key in keys:
        if not isinstance(current, dict):
            return default
        current = current.get(key)
    if current is None:
        return default
    return current


def _calibration_metadata():
    return {
        'calibration_source': str(PLATE_DETECTION_CALIBRATION.get('loaded_from', 'builtin_default')),
        'calibration_path': str(PLATE_DETECTION_CALIBRATION.get('calibration_path', '')),
    }


PLATE_QUALITY_ASPECT_TARGET = _clamp(
    _parse_float(os.environ.get('GROM_OCR_PLATE_QUALITY_ASPECT_TARGET'), _parse_float(_calibration_value('quality', 'aspect_target', default=4.2), 4.2)),
    3.4,
    5.4,
)
PLATE_QUALITY_ASPECT_TOLERANCE = _clamp(
    _parse_float(os.environ.get('GROM_OCR_PLATE_QUALITY_ASPECT_TOLERANCE'), _parse_float(_calibration_value('quality', 'aspect_tolerance', default=1.8), 1.8)),
    1.0,
    3.5,
)
PLATE_QUALITY_ASPECT_MIN = _clamp(
    _parse_float(os.environ.get('GROM_OCR_PLATE_QUALITY_ASPECT_MIN'), _parse_float(_calibration_value('quality', 'aspect_min', default=1.5), 1.5)),
    1.0,
    3.0,
)
PLATE_QUALITY_ASPECT_MAX = _clamp(
    _parse_float(os.environ.get('GROM_OCR_PLATE_QUALITY_ASPECT_MAX'), _parse_float(_calibration_value('quality', 'aspect_max', default=8.5), 8.5)),
    5.0,
    12.0,
)
PLATE_QUALITY_MIN_AREA = max(3000, min(_parse_int(os.environ.get('GROM_OCR_PLATE_QUALITY_MIN_AREA'), _parse_int(_calibration_value('quality', 'min_area', default=4500), 4500)), 30000))


def _as_bgr(img):
    if img is None or getattr(img, 'size', 0) == 0:
        return None
    if len(img.shape) == 2:
        return cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    return img


def _as_gray(img):
    if img is None or getattr(img, 'size', 0) == 0:
        return None
    if len(img.shape) == 2:
        return img
    return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


def order_points(points):
    """Return a stable tl, tr, br, bl ordering for a quadrilateral."""
    pts = np.asarray(points, dtype='float32')
    if pts.ndim != 2 or pts.shape[0] < 4 or pts.shape[1] != 2:
        raise ValueError('quadrilateral_points_required')

    rect = np.zeros((4, 2), dtype='float32')
    sums = pts.sum(axis=1)
    diffs = np.diff(pts, axis=1).reshape(-1)

    rect[0] = pts[np.argmin(sums)]  # top-left
    rect[2] = pts[np.argmax(sums)]  # bottom-right
    rect[1] = pts[np.argmin(diffs)]  # top-right
    rect[3] = pts[np.argmax(diffs)]  # bottom-left
    return rect


def warp_rotated_rect(img, rect, pad_ratio=0.15, min_size=(70, 22)):
    """Perspective-correct a rotated rectangle crop.

    The function expands the rotated rect slightly, projects it to a canonical
    horizontal rectangle and returns the rectified crop. It is safe to use on
    the contour-based plate proposals generated by the main detector.
    """
    if img is None or getattr(img, 'size', 0) == 0 or rect is None:
        return None

    try:
        (center_x, center_y), (width, height), angle = rect
    except Exception:
        return None

    width = float(width)
    height = float(height)
    if width <= 1.0 or height <= 1.0:
        return None

    scale = 1.0 + max(0.0, float(pad_ratio)) * 2.0
    expanded_rect = ((float(center_x), float(center_y)), (width * scale, height * scale), float(angle))
    box = cv2.boxPoints(expanded_rect).astype('float32')
    try:
        ordered = order_points(box)
    except Exception:
        return None

    width_a = float(np.linalg.norm(ordered[1] - ordered[0]))
    width_b = float(np.linalg.norm(ordered[2] - ordered[3]))
    height_a = float(np.linalg.norm(ordered[3] - ordered[0]))
    height_b = float(np.linalg.norm(ordered[2] - ordered[1]))

    max_width = int(round(max(width_a, width_b)))
    max_height = int(round(max(height_a, height_b)))
    min_width = int(min_size[0])
    min_height = int(min_size[1])
    if max_width < min_width or max_height < min_height:
        return None

    destination = np.array(
        [
            [0.0, 0.0],
            [max_width - 1.0, 0.0],
            [max_width - 1.0, max_height - 1.0],
            [0.0, max_height - 1.0],
        ],
        dtype='float32',
    )
    matrix = cv2.getPerspectiveTransform(ordered, destination)
    warped = cv2.warpPerspective(
        img,
        matrix,
        (max_width, max_height),
        flags=cv2.INTER_CUBIC,
        borderMode=cv2.BORDER_REPLICATE,
    )
    if warped is None or getattr(warped, 'size', 0) == 0:
        return None
    return warped


def crop_axis_aligned_box(img, box, pad_ratio=0.08, min_size=(70, 22)):
    """Crop a standard axis-aligned box with a small padded margin."""
    if img is None or getattr(img, 'size', 0) == 0 or not box:
        return None

    if isinstance(box, dict) and {'x', 'y', 'w', 'h'}.issubset(box):
        x1 = int(round(float(box.get('x', 0))))
        y1 = int(round(float(box.get('y', 0))))
        x2 = x1 + int(round(float(box.get('w', 0))))
        y2 = y1 + int(round(float(box.get('h', 0))))
    elif isinstance(box, dict) and {'xmin', 'ymin', 'xmax', 'ymax'}.issubset(box):
        x1 = int(round(float(box.get('xmin', 0))))
        y1 = int(round(float(box.get('ymin', 0))))
        x2 = int(round(float(box.get('xmax', 0))))
        y2 = int(round(float(box.get('ymax', 0))))
    else:
        return None

    height, width = img.shape[:2]
    x1 = _clamp(x1, 0, width)
    x2 = _clamp(x2, 0, width)
    y1 = _clamp(y1, 0, height)
    y2 = _clamp(y2, 0, height)
    if x2 <= x1 or y2 <= y1:
        return None

    box_w = x2 - x1
    box_h = y2 - y1
    pad_x = int(round(box_w * max(0.0, float(pad_ratio))))
    pad_y = int(round(box_h * max(0.0, float(pad_ratio))))

    x1 = _clamp(x1 - pad_x, 0, width)
    y1 = _clamp(y1 - pad_y, 0, height)
    x2 = _clamp(x2 + pad_x, 0, width)
    y2 = _clamp(y2 + pad_y, 0, height)
    if x2 <= x1 or y2 <= y1:
        return None

    crop = img[y1:y2, x1:x2]
    if crop is None or getattr(crop, 'size', 0) == 0:
        return None
    if crop.shape[0] < min_size[1] or crop.shape[1] < min_size[0]:
        return None
    return crop


def _rotate_image(image, angle):
    if image is None or getattr(image, 'size', 0) == 0 or abs(float(angle)) < 0.001:
        return image
    height, width = image.shape[:2]
    matrix = cv2.getRotationMatrix2D((width / 2.0, height / 2.0), float(angle), 1.0)
    return cv2.warpAffine(
        image,
        matrix,
        (width, height),
        flags=cv2.INTER_CUBIC,
        borderMode=cv2.BORDER_REPLICATE,
    )


def estimate_plate_skew_angle(img):
    gray = _as_gray(img)
    if gray is None or getattr(gray, 'size', 0) == 0:
        return 0.0

    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    threshold = cv2.adaptiveThreshold(
        blurred,
        255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV,
        31,
        11,
    )
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    threshold = cv2.morphologyEx(threshold, cv2.MORPH_CLOSE, kernel, iterations=1)

    points = cv2.findNonZero(threshold)
    if points is None or len(points) < 24:
        return 0.0

    rect = cv2.minAreaRect(points)
    angle = float(rect[-1])
    if angle < -45.0:
        angle += 90.0
    if angle > 45.0:
        angle -= 90.0

    if abs(angle) < 0.8 or abs(angle) > 18.0:
        return 0.0
    return round(float(angle), 2)


def normalize_plate_crop(img, pad_ratio=0.06, deskew_min_angle=0.75, target_long_side=None):
    """Create a conservative OCR-friendly canonical plate crop."""
    if img is None or getattr(img, 'size', 0) == 0:
        return img

    candidate = img
    angle = estimate_plate_skew_angle(candidate)
    if abs(angle) >= float(deskew_min_angle):
        candidate = _rotate_image(candidate, -angle)

    if candidate is None or getattr(candidate, 'size', 0) == 0:
        return img

    height, width = candidate.shape[:2]
    aspect_ratio = float(width) / float(max(1, height))
    if 1.15 <= aspect_ratio <= 2.3:
        mid = height // 2
        top_half = candidate[0:mid, :]
        bottom_half = candidate[mid:height, :]
        if bottom_half.shape[0] != top_half.shape[0]:
            bottom_half = cv2.resize(bottom_half, (top_half.shape[1], top_half.shape[0]))
        candidate = cv2.hconcat([top_half, bottom_half])

    if pad_ratio and pad_ratio > 0:
        height, width = candidate.shape[:2]
        border = max(2, int(round(min(height, width) * float(pad_ratio))))
        border = min(border, max(8, min(height, width) // 3))
        if border > 0:
            candidate = cv2.copyMakeBorder(candidate, border, border, border, border, cv2.BORDER_REPLICATE)

    if target_long_side and target_long_side > 0:
        height, width = candidate.shape[:2]
        longest = max(height, width)
        if longest > 0 and longest < target_long_side:
            scale = float(target_long_side) / float(longest)
            target_w = max(32, int(round(width * scale)))
            target_h = max(32, int(round(height * scale)))
            candidate = cv2.resize(candidate, (target_w, target_h), interpolation=cv2.INTER_CUBIC)

    return candidate


def _plate_style_signature(img):
    bgr = _as_bgr(img)
    if bgr is None or getattr(bgr, 'size', 0) == 0:
        return {
            'style_hint': 'indefinida',
            'style_confidence': 0.0,
            'color_saturation': 0.0,
            'gray_ratio': 0.0,
            'white_ratio': 0.0,
            'blue_ratio': 0.0,
            'blue_band_ratio': 0.0,
            'style_strength': 0.0,
            'style_competing_strength': 0.0,
        }

    hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
    height = hsv.shape[0]
    top_height = max(1, int(round(height * 0.32)))
    top_band = hsv[:top_height, :, :]

    hue = hsv[:, :, 0].astype(np.float32)
    sat = hsv[:, :, 1].astype(np.float32)
    val = hsv[:, :, 2].astype(np.float32)
    top_hue = top_band[:, :, 0].astype(np.float32)
    top_sat = top_band[:, :, 1].astype(np.float32)
    top_val = top_band[:, :, 2].astype(np.float32)

    color_saturation = float(np.mean(sat))
    color_value = float(np.mean(val))
    gray_ratio = float(np.mean(sat <= 24.0) * 100.0)
    white_ratio = float(np.mean((val >= 190.0) & (sat <= 45.0)) * 100.0)
    blue_ratio = float(np.mean((hue >= 95.0) & (hue <= 135.0) & (sat >= 36.0) & (val >= 60.0)) * 100.0)
    blue_band_ratio = float(np.mean((top_hue >= 95.0) & (top_hue <= 135.0) & (top_sat >= 36.0) & (top_val >= 60.0)) * 100.0)

    mercosul_strength = 0.0
    mercosul_strength += min(0.50, blue_band_ratio / 24.0)
    mercosul_strength += min(0.22, blue_ratio / 28.0)
    mercosul_strength += min(0.12, max(0.0, color_saturation - 24.0) / 140.0)
    mercosul_strength += min(0.08, white_ratio / 80.0)

    antigo_strength = 0.0
    antigo_strength += min(0.50, gray_ratio / 68.0)
    antigo_strength += min(0.20, max(0.0, 28.0 - color_saturation) / 32.0)
    antigo_strength += min(0.10, max(0.0, 180.0 - color_value) / 180.0)
    antigo_strength += min(0.10, white_ratio / 90.0)

    style_hint = 'indefinida'
    style_confidence = 0.0
    competing_strength = min(1.0, max(mercosul_strength, antigo_strength))
    if mercosul_strength >= 0.58 and mercosul_strength >= antigo_strength + 0.08:
        style_hint = 'mercosul'
        style_confidence = min(97.0, 52.0 + mercosul_strength * 40.0)
    elif antigo_strength >= 0.58 and antigo_strength >= mercosul_strength + 0.08:
        style_hint = 'antigo'
        style_confidence = min(97.0, 52.0 + antigo_strength * 40.0)
    else:
        style_confidence = max(0.0, (competing_strength - 0.30) * 70.0)

    return {
        'style_hint': style_hint,
        'style_confidence': round(float(style_confidence), 1),
        'color_saturation': round(float(color_saturation), 2),
        'gray_ratio': round(float(gray_ratio), 2),
        'white_ratio': round(float(white_ratio), 2),
        'blue_ratio': round(float(blue_ratio), 2),
        'blue_band_ratio': round(float(blue_band_ratio), 2),
        'style_strength': round(float(max(mercosul_strength, antigo_strength)), 3),
        'style_competing_strength': round(float(min(mercosul_strength, antigo_strength)), 3),
    }


def describe_plate_crop(img):
    """Return a compact quality report for a plate candidate."""
    if img is None or getattr(img, 'size', 0) == 0:
        return {
            'quality_score': 0.0,
            'quality_label': 'critica',
            'aspect_ratio': 0.0,
            'area': 0,
            'brightness': 0.0,
            'contrast': 0.0,
            'sharpness': 0.0,
            'dynamic_range': 0.0,
            'edge_density': 0.0,
            'foreground_ratio': 0.0,
            'shape_hint': 'indefinida',
            'style_hint': 'indefinida',
            'style_confidence': 0.0,
            'color_saturation': 0.0,
            'gray_ratio': 0.0,
            'white_ratio': 0.0,
            'blue_ratio': 0.0,
            'blue_band_ratio': 0.0,
            'style_strength': 0.0,
            'style_competing_strength': 0.0,
            **_calibration_metadata(),
        }

    gray = _as_gray(img)
    if gray is None:
        return {
            'quality_score': 0.0,
            'quality_label': 'critica',
            'aspect_ratio': 0.0,
            'area': 0,
            'brightness': 0.0,
            'contrast': 0.0,
            'sharpness': 0.0,
            'dynamic_range': 0.0,
            'edge_density': 0.0,
            'foreground_ratio': 0.0,
            'shape_hint': 'indefinida',
            **_calibration_metadata(),
        }

    height, width = gray.shape[:2]
    area = int(height * width)
    aspect_ratio = float(width) / float(max(1, height))
    brightness = float(np.mean(gray))
    contrast = float(np.std(gray))
    sharpness = float(cv2.Laplacian(gray, cv2.CV_64F).var())
    p95, p5 = np.percentile(gray, [95, 5])
    dynamic_range = float(p95 - p5)
    edge_density = float(np.mean(cv2.Canny(gray, 80, 200) > 0) * 100.0)
    foreground_ratio = float(np.mean((gray > 18) & (gray < 242)) * 100.0)

    aspect_score = 1.0 - min(1.0, abs(aspect_ratio - PLATE_QUALITY_ASPECT_TARGET) / max(0.001, PLATE_QUALITY_ASPECT_TOLERANCE))
    if aspect_ratio < PLATE_QUALITY_ASPECT_MIN or aspect_ratio > PLATE_QUALITY_ASPECT_MAX:
        aspect_score *= 0.55
    elif aspect_ratio < (PLATE_QUALITY_ASPECT_TARGET - 1.4) or aspect_ratio > (PLATE_QUALITY_ASPECT_TARGET + 1.4):
        aspect_score *= 0.82

    size_score = min(1.0, area / float(PLATE_QUALITY_MIN_AREA))
    contrast_score = min(1.0, contrast / 70.0)
    sharpness_score = min(1.0, sharpness / 360.0)
    dynamic_score = min(1.0, dynamic_range / 170.0)
    edge_score = min(1.0, edge_density / 8.5)
    brightness_score = 1.0 - min(1.0, abs(brightness - 128.0) / 128.0)
    foreground_score = min(1.0, foreground_ratio / 82.0)

    quality = (
        (sharpness_score * 0.26)
        + (contrast_score * 0.20)
        + (dynamic_score * 0.14)
        + (edge_score * 0.12)
        + (size_score * 0.12)
        + (aspect_score * 0.12)
        + (brightness_score * 0.02)
        + (foreground_score * 0.02)
    ) * 100.0

    if aspect_ratio >= 3.2 and aspect_ratio <= 5.8:
        quality *= 1.05
    elif 1.2 <= aspect_ratio <= 2.2:
        quality *= 1.02
    elif aspect_ratio < 1.0 or aspect_ratio > 7.5:
        quality *= 0.86
    if sharpness < 60.0:
        quality *= 0.86
    if contrast < 20.0:
        quality *= 0.84
    if dynamic_range < 70.0:
        quality *= 0.88
    if aspect_ratio < 0.9 or aspect_ratio > 8.5:
        quality *= 0.72
    elif aspect_ratio > 6.5:
        quality *= 0.88
    if area < 4500:
        quality *= 0.74
    elif area < 9000:
        quality *= 0.88
    if area < 6000:
        quality *= 0.75

    quality = _clamp(float(quality), 0.0, 100.0)
    if quality >= 82.0:
        label = 'excelente'
    elif quality >= 66.0:
        label = 'boa'
    elif quality >= 46.0:
        label = 'regular'
    else:
        label = 'critica'

    if aspect_ratio >= 3.4:
        shape_hint = 'wide'
    elif aspect_ratio >= 2.0:
        shape_hint = 'compacta'
    else:
        shape_hint = 'vertical'

    style = _plate_style_signature(img)

    return {
        'quality_score': round(float(quality), 1),
        'quality_label': label,
        'aspect_ratio': round(float(aspect_ratio), 3),
        'area': area,
        'brightness': round(float(brightness), 2),
        'contrast': round(float(contrast), 2),
        'sharpness': round(float(sharpness), 2),
        'dynamic_range': round(float(dynamic_range), 2),
        'edge_density': round(float(edge_density), 2),
        'foreground_ratio': round(float(foreground_ratio), 2),
        'shape_hint': shape_hint,
        **style,
        **_calibration_metadata(),
    }


def enhance_plate_preview(img, target_long_side=520):
    """Apply a mild, visually pleasing enhancement for report previews.

    The transformations are intentionally conservative: brightness balancing,
    local contrast, light denoising and a restrained sharpening pass.
    """
    if img is None or getattr(img, 'size', 0) == 0:
        return img

    candidate = _as_bgr(img)
    if candidate is None:
        return img

    gray = _as_gray(candidate)
    if gray is None:
        return candidate

    brightness = float(np.mean(gray))
    contrast = float(np.std(gray))
    blur = float(cv2.Laplacian(gray, cv2.CV_64F).var())

    if brightness < 100.0:
        candidate = cv2.convertScaleAbs(candidate, alpha=1.18, beta=15)
    elif brightness > 188.0:
        candidate = cv2.convertScaleAbs(candidate, alpha=0.91, beta=-12)

    lab = cv2.cvtColor(candidate, cv2.COLOR_BGR2LAB)
    l_channel, a_channel, b_channel = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=1.7, tileGridSize=(8, 8))
    l_channel = clahe.apply(l_channel)
    balanced = cv2.cvtColor(cv2.merge((l_channel, a_channel, b_channel)), cv2.COLOR_LAB2BGR)

    if contrast < 38.0 or blur < 120.0:
        balanced = cv2.bilateralFilter(balanced, 5, 42, 42)

    sharpen_kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]], dtype='float32')
    sharpened = cv2.filter2D(balanced, -1, sharpen_kernel)
    preview = cv2.addWeighted(balanced, 0.82, sharpened, 0.18, 0)

    height, width = preview.shape[:2]
    longest = max(height, width)
    target_long_side = int(max(240, target_long_side))
    if longest < target_long_side:
        scale = target_long_side / float(longest)
        target_w = max(32, int(round(width * scale)))
        target_h = max(32, int(round(height * scale)))
        preview = cv2.resize(preview, (target_w, target_h), interpolation=cv2.INTER_CUBIC)
    elif longest > 1600:
        scale = 1600.0 / float(longest)
        target_w = max(32, int(round(width * scale)))
        target_h = max(32, int(round(height * scale)))
        preview = cv2.resize(preview, (target_w, target_h), interpolation=cv2.INTER_AREA)

    return preview
